[project]
name = "uart_16550_veryl"
version = "0.1.0"
[build]
clock_type = "posedge"
reset_type = "sync_low"
sources = ["src", "test"]
target = {type = "directory", path = "target"}
[test.verilator]
compile_args = ["-Wno-WIDTHEXPAND"]